apiVersion: apps/v1
kind: Deployment
metadata:
  name: azla-workload-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-1
  template:
    metadata:
      labels:
        app: nginx-1
        color: lime
    spec:
      containers:
        - name: nginx
          image: nginx:1.18
          ports:
            - containerPort: 80
          envFrom:
          - secretRef:                
              name: azla-secret
      nodeSelector:
        kubernetes.io/os: linux
