apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: azla-scaler
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: azla-workload-dep
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 12
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: false        # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: 30
          policies:
          - type: Percent
            value: 100
            periodSeconds: 1   
  triggers:
  - type: azure-log-analytics
    metadata:      
      query: |
        let AppName = "complex";
        let ClusterName = "kizaks";
        let AvgDuration = ago(5m);
        let ThresholdCoefficient = 0.8;
        Perf
        | where InstanceName contains AppName
        | where InstanceName contains ClusterName
        | where CounterName == "cpuUsageNanoCores"
        | where TimeGenerated > AvgDuration
        | extend AppName = substring(InstanceName, indexof((InstanceName), "/", 0, -1, 10) + 1)
        | summarize MetricValue=round(avg(CounterValue)) by CounterName, AppName
        | join (Perf 
                | where InstanceName contains AppName
                | where InstanceName contains ClusterName
                | where CounterName == "cpuLimitNanoCores"
                | where TimeGenerated > AvgDuration
                | extend AppName = substring(InstanceName, indexof((InstanceName), "/", 0, -1, 10) + 1)
                | summarize arg_max(TimeGenerated, *) by AppName, CounterName
                | project Limit = CounterValue, TimeGenerated, CounterPath, AppName)
                on AppName
        | project MetricValue, Threshold = 50000000
      threshold: "50000000"
      tenantIdFromEnv: azla-tenantId
      clientIdFromEnv: azla-clientId
      clientSecretFromEnv: azla-clientSecret
      workspaceIdFromEnv: azla-workspaceId