apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pvc-pod-ss
spec:
  replicas: 2
  serviceName: pvc-pod-svc
  selector:
    matchLabels:
       target: pvc-ss-pod       
  template:
    metadata:
      name: pvc-ss-pod
      labels:
        target: pvc-ss-pod
        color: aqua
    spec:
      nodeSelector:            
        kubernetes.io/os: linux 
      containers:
      - name: nginx
        image: k8slab/nginx:1.0
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: "/usr/ss"
          name: ss-azure-disk
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: target
                operator:  In
                values:
                - pvc-ss-pod
            topologyKey: "kubernetes.io/hostname"             
  volumeClaimTemplates:
  - metadata:
      name: ss-azure-disk
    spec:
      storageClassName: default  
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pvc-pod-svc
spec:
  ports:
  - port: 80
  clusterIP: None
  selector:
    app: pvc-pod
