apiVersion: apps/v1
kind: Deployment
metadata:
  name: azla-complex-web-load
spec:
  selector:
    matchLabels:
      run: cw-load-generator
  replicas: 1
  template:
    metadata:
      labels:
        run: cw-load-generator
    spec:
      containers:
      - name: cw-load-generator
        image: busybox
        args:
        - /bin/sh
        - -c
        - while sleep 0.01; do wget -q -O- http://azla-complex-web-svc; echo " Sent"; done
        imagePullPolicy: Always
